<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoArticle\Module'                       => __DIR__ . '/Module.php',
    'UthandoArticle\Controller\ArticleController' => __DIR__ . '/src/UthandoArticle/Controller/ArticleController.php',
    'UthandoArticle\Form\Article'                 => __DIR__ . '/src/UthandoArticle/Form/Article.php',
    'UthandoArticle\Form\ArticleFieldSet'         => __DIR__ . '/src/UthandoArticle/Form/ArticleFieldSet.php',
    'UthandoArticle\Form\Element\ResourceList'    => __DIR__ . '/src/UthandoArticle/Form/Element/ResourceList.php',
    'UthandoArticle\Hydrator\Article'             => __DIR__ . '/src/UthandoArticle/Hydrator/Article.php',
    'UthandoArticle\InputFilter\Article'          => __DIR__ . '/src/UthandoArticle/InputFilter/Article.php',
    'UthandoArticle\Mapper\Article'               => __DIR__ . '/src/UthandoArticle/Mapper/Article.php',
    'UthandoArticle\Model\Article'                => __DIR__ . '/src/UthandoArticle/Model/Article.php',
    'UthandoArticle\Service\Article'              => __DIR__ . '/src/UthandoArticle/Service/Article.php',
    'UthandoArticle\View\GetPost'                 => __DIR__ . '/src/UthandoArticle/View/GetPost.php',
    'UthandoArticle\View\RecentPosts'             => __DIR__ . '/src/UthandoArticle/View/RecentPosts.php',
);
