<?php
$form = $this->form;
$routeArray = array('action' => $this->formAction);
if (isset($this->articleId)) $routeArray['id'] = $this->articleId;
?>
<div class="row">
    <form class="col-md-12 form form-horizontal" method="post" action="<?=$this->url('admin/article/edit', $routeArray) ?>">
        <fieldset>
        <legend><?=ucwords($this->formAction); ?> Article Form:</legend>
        <div class="row">
            <div class="col-sm-6">
                <fieldset>
           	        <legend>Article Details</legend>
                    <div class="form-group<?php if ($form->get('title')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="title"><?=$form->get('title')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('title')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('title'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>
                    
                     <div class="form-group<?php if ($form->get('slug')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="slug"><?=$form->get('slug')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('slug')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('slug'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>
                    
                     <div class="form-group<?php if ($form->get('description')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="description"><?=$form->get('description')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get('description')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('description'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>
                </fieldset>
           	</div>
            
            <div class="col-sm-6">
                <fieldset>
           	        <legend>Menu</legend>
           	        
                    <?=$this->navigationForm(); ?>
                    
           	        <div class="form-group">
                        <div class="col-md-offset-4 col-md-8">
                             <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType1" value="noInsert" checked >
                                do not add to menu/no change.
                            </label>
                       	    <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType2" value="insert">
                                insert after this page.
                            </label>
                            <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType3" value="insertSub">
                                insert as a subpage of this page.
                            </label>
                        </div>
                    </div>
                </fieldset>
           	</div>
        </div>
        
        <div class="row">
                <div class="col-md-12">
                <fieldset>
                    <legend>HTML Content</legend>
                    <?=$this->formElement($form->get('content')->setAttribute('class', 'form-control')); ?>
                </fieldset>
            </div>
        </div>
                
        <?=$this->formElement($form->get('articleId')); ?>
        <?=$this->formElement($form->get('pageHits')); ?>
        <input type="hidden" name="action" value="<?=$this->formAction; ?>">
        
        <div class="clearfix">&nbsp;</div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary" 
                data-loading-text="Please wait...">Submit</button>
                <button type="button" class="btn btn-warning" 
                data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('admin/article', array(
                        'action' => 'list',
                    )) ?>';">Cancel</button>
            </div>
        </div>
        </fieldset>
    </form>
</div>

