<?php $this->headTitle('Edit Article') ?>
<?php $this->layout()->pageTitle = $this->translate('Edit Article');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-article" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/article');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-article',
    'action' => $this->url('admin/article/edit', [
        'action' => 'edit',
        'id' => $this->model->getArticleId()
    ]),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Edit Article');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>

<?php $this->textEditor()->summernote();?>
<?php $this->fileManager()->uploadButton('article-image', 'article-image-button');?>

