<?php $this->headTitle('Article') ?>
<?php $this->layout()->pageTitle = $this->translate('Article');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<a href="<?=$this->url('admin/article/edit', [
	'action' => 'add'
]);?>" type="submit" data-toggle="tooltip" title="<?=$this->translate('Add Article');?>" class="btn btn-primary">
	<i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('Article List');?></h3>
	</div>
	<div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'article',
            'searchInputs'	=> [
                $this->translate('Article') => 'title',
            ],
        ]);?>
	</div>
    <div id="table-article" class="admin-table">
        <?=$this->partial('uthando-article/article/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-article').dataGrid({
    	url : 'article/list',
    	query: { sort : 'articleId' },
    	searchForm : $('#search-article'),
    	paging : 'links',
    	columnSort: true
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
