
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'article',
	'searchInputs'	=> [
		'Article' => 'title',
	],
]);?>

<div id="table-article">
	<?=$this->partial('uthando-article/article/list', [
	    'models' => $this->models
	]); ?>
</div>


<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-article').dataGrid({
    	url : 'article/list',
    	query: { sort : 'articleId' },
    	searchForm : $('#search-article'),
    	paging : 'links',
    	columnSort: true
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
