
<div class="modal-header"><!-- modal header -->
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title"><?=$this->page->getTitle();?></h4>
</div><!-- /modal header -->

<!-- modal body -->
<div class="modal-body">
	<?=$this->page->getContent();?>
</div>
<!-- /modal body -->

<div class="modal-footer"><!-- modal footer -->
	<button class="btn btn-primary" data-dismiss="modal">Close</button>
</div><!-- /modal footer -->