<?php 
$articleTitle = $this->escapehtml($this->page->getTitle());
$this->headTitle($articleTitle);
$splitTitle = explode(' ', $articleTitle);
$title2 = end($splitTitle);
array_pop($splitTitle);
$title1 = implode(' ', $splitTitle);

// setting page keywords and description
if ($this->page->getDescription() || $this->page->getDescription() != '') {
    $this->headMeta()->appendName('description', $this->escapehtml($this->page->getDescription()));
}
?>
<?php if ($this->page->getSlug() != 'welcome'): ?>
<div>
	<h2><?=$title1; ?> <span class="theme-color"><?=$title2; ?></span></h2>
	<hr>
</div>
<?php endif; ?>

<?php echo $this->page->getContent(); ?>
